version: '3'

services:

  profil:
    container_name: mtheos/profil
    image: mtheos/profil
    build:
      context: profil
      dockerfile: Dockerfile
      args:
        JAR_FILE: target/profil-0.0.1-SNAPSHOT.jar
    expose:
      - 8080
    ports:
      - 8080:8080

  matching:
    container_name: mtheos/matching
    image: mtheos/matching
    build:
      context: matching
      dockerfile: Dockerfile
      args:
        JAR_FILE: target/matching-0.0.1-SNAPSHOT.jar
    expose:
      - 8080
    ports:
      - 8081:8080

  procedures:
    container_name: mtheos/procedures
    image: mtheos/procedures
    build:
      context: procedures
      dockerfile: Dockerfile
      args:
        JAR_FILE: target/procedures-0.0.1-SNAPSHOT.jar
    expose:
      - 8080
    ports:
      - 8082:8080