version: '3'

services:

  profil:
    container_name: profil
    image: profil
    build:
      context: profil
      dockerfile: Dockerfile
      args:
        JAR_FILE: target/profil-0.0.1-SNAPSHOT.jar
    expose:
      - 8080
    ports:
      - 8080:8080

  matching:
    container_name: matching
    image: matching
    build:
      context: matching
      dockerfile: Dockerfile
      args:
        JAR_FILE: target/matching-0.0.1-SNAPSHOT.jar
    expose:
      - 8080
    ports:
      - 8081:8080